### ISSUE TITLE
How to get output with unplaced contigs not concatenated?

### ISSUE THREAD

**Issue by stacy734** [malonge/RagTag#5] opened 2020-06-22 15:52 UTC
Hello,
I'd like to have the output with unplaced contigs returned as individual (original) sequences, not concatenated.
I have tried both with and without the -C option, but either way the unplaced contigs are returned concatenated into one big sequence.
Is that expected?
Thanks for making this great resource available to all of us.
Stacy

**Comment by malonge** [comment] 2020-06-22 15:56
Hi Stacy,

Thanks for bringing this up. Indeed, what you request should be the default behavior. Using default settings (without `-C`), could you share an example line from the AGP (`ragtag.scaffolds.agp`) file for an unplaced contig.

**Comment by stacy734** [comment] 2020-06-22 16:03
I should have mentioned, I'm referring to the output file (ragtag.scaffolds.fasta), not the AGP file.
Should that also be the default setting for the resulting fasta?

**Comment by malonge** [comment] 2020-06-22 16:18
Yes, it should be the same for both. Actually, the AGP file defines the fasta file, so it gives us the same info.

So whatever the fasta header is for the concatenated sequence, we should also see it in the AGP file.

**Comment by stacy734** [comment] 2020-06-22 17:00
Thanks Malonge.
I may have misinterpreted the numbers I was seeing.
I am starting with a file with 1,391,128 contigs. I have run RagTag with and without the -C options.  
In each case, RagTag was able to place 96 contigs (as expected).
Running with the -C option gives an output of 94 contigs in ragtag.scaffolds.fasta (as expceted).
Running without the -C option gives an output of 46556 contigs.  (not expected).  In this case I would expect to see an output with over a million contigs.  
I will post the results and original files.  Please let me know if my expectations are flawed.
And thank you again for your super-fast response.
Stacy

**Comment by malonge** [comment] 2020-06-22 17:28
Hi Stacy,

Thanks for the clarification. I suppose the answer lies in the discrepancy between 96 placed contigs and what would be suggested by the number of output contigs (46556).

How are you calculating that only 96 contigs were placed?

Also, in case it is helpful for debugging, the. `-j` option allows the user to specify a list of contigs to automatically leave unplaced.

**Comment by malonge** [comment] 2020-06-22 17:28
If you share the AGP file with me I can take a deeper look. Perhaps you could share here, or email me at `malonge11@gmail.com`

**Comment by stacy734** [comment] 2020-06-22 17:51
Yes, exactly: the discrepancy between the 96 placed contigs and the 46556 output contigs.
The output file: ragtag.scaffolds.stats showed 96 placed sequences (first column) for both runs, with and without -C.

Also notable: 

The original file contains 2,101,963,778 bases.

The results of both RagTag runs gave results with an identical number of bases (expected) but the number of bases is 1,017,348,354 (not expected) seems small compared to the starting size.

I'm loading the original files to a server now.

**Comment by malonge** [comment] 2020-06-22 18:14
ok perhaps I see a hint for where the confusion is. The first column of the AGP file refers to the scaffolds, not the contigs. So when considering what is "placed" vs. "unplaced", one should look at column 6.

When a contig is unplaced, column 1 and column 6 should be the same value (unless you specify `-u`, which just appends a suffix to column 1 for unplaced sequences)

**Comment by stacy734** [comment] 2020-06-22 19:23
[ragtag.scaffolds.agp.txt](https://github.com/malonge/RagTag/files/4815136/ragtag.scaffolds.agp.txt)
[ragtag.scaffolds.stats.txt](https://github.com/malonge/RagTag/files/4815157/ragtag.scaffolds.stats.txt)

Thanks Michael, that clears things up a lot.

I have attached the files ragtag.scaffolds.agp.txt and ragtag.scaffolds.stats.txt (txt extensions to make it acceptable as a github attachment.)  These files were generated without the -C parameter.

The input file has contains 2,101,963,778 bases and 1,391,128 sequences.
The output file has  1,017,348,354 bases and 46556 sequences.

Based on the attached agp file, does that seem right?   It seems that either some of the input sequences are not represented in the output file, or it is a major improvement on the assembly.   I'm hoping for the latter.   :)

**Comment by malonge** [comment] 2020-06-22 19:47
ok so it looks like the unplaced contigs are not being concatenated. For example, ragtag.scaffolds.fasta should have `NW_019105540.1_RagTag`, a single unplaced contig that came from `NW_019105540.1`.

So the question is, where did all the other contigs go? Could you share the fai file for your query contigs? And while you are at it, could you share the exact command you used for ragtag?

**Comment by malonge** [comment] 2020-06-22 19:54
To follow up, the AGP file and the stats indicate that only 46559 contigs ended up in the final AGP/fasta file. RagTag is designed so that every single contig should be in there. 

So if you give me the fai file for the contigs, I can find an example contig that did not make it through.

**Comment by stacy734** [comment] 2020-06-22 21:13
[GCF_000757685.1_NilLug1.0_genomic.fna.fai.gz](https://github.com/malonge/RagTag/files/4815587/GCF_000757685.1_NilLug1.0_genomic.fna.fai.gz)

I have attached the *fai file.

The command used was:
ragtag.py scaffold -u SRR11513119.fasta GCF_000757685.1_NilLug1.0_genomic.fna &

Note: **SRR11513119.fasta** is the fasta to be mapped (with 1,391,128 sequences).  Each sequence header starts with SRR*.
**GCF_000757685.1_NilLug1.0_genomic.fna** is the reference.  Each sequence header starts with NW*

All the headers in the *fai file start with NW*, same as the reference.   Does that sound right?

**Comment by stacy734** [comment] 2020-06-22 21:24
I just realized that the reference genome:
https://www.ncbi.nlm.nih.gov/assembly/GCF_000757685.1
Has 46,559 sequences.
Maybe the command I provided actually mapped the reference to my own contigs, instead of the intended mapping of my contigs to the reference?

**Comment by stacy734** [comment] 2020-06-22 21:30
All of the files, including reference and output, can be found here:
https://tinyurl.com/ydcqets6
filename: ragtag_test.tar.gz

Thanks again for taking the time to help with this.

**Comment by malonge** [comment] 2020-06-22 21:37
Hi there,

Yes I think the problem is just that the query and reference need to be switched. So use this command instead:

`ragtag.py scaffold -u GCF_000757685.1_NilLug1.0_genomic.fna SRR11513119.fasta`

I might have caused some confusion because this is a backwards incompatibility with RaGOO, where the order is reversed. But I changed it for RagTag since this way seems to be conventional.

I am going to close this for now but please let me know if you continue to have problems. 

Thanks!

**Closed by malonge** 2020-06-22 21:37 UTC

**Comment by stacy734** [comment] 2020-06-22 21:39
I love easy solutions!
Thanks!
