### ISSUE TITLE
KeyError: "sequence 'ctg002980_np1212' not present"

### ISSUE THREAD

**Issue by DengHAU** [malonge/RagTag#14] opened 2020-07-30 03:43 UTC
Hi,

When I used `ragtag.py` to do scaffolding, the pipelie died at runing `ragtag_agp2fasta.py` and reported "can't not find sequence error". 
Thu Jul 30 02:21:33 2020 --- Running: ragtag_agp2fasta.py 
/genome/g41/ragtag_output/ragtag.scaffolds.agp 
/genome/g41/genome.nextpolish.fa > genome/g41/ragtag_output/ragtag.scaffolds.fasta
Traceback (most recent call last):
  File "/public/home/miniconda3/envs/ngs/bin/ragtag_agp2fasta.py", line 74, in <module>
    main()
  File "/public/home/miniconda3/envs/ngs/bin/ragtag_agp2fasta.py", line 67, in main
    sys.stdout.write(fai.fetch(agp_line.comp))
  File "pysam/libcfaidx.pyx", line 303, in pysam.libcfaidx.FastaFile.fetch
KeyError: "sequence 'ctg002980_np1212' not present"
Traceback (most recent call last):
  File "/public/home/miniconda3/envs/ngs/bin/ragtag_scaffold.py", line 528, in <module>
    main()
  File "/public/home/miniconda3/envs/ngs/bin/ragtag_scaffold.py", line 516, in main
    run_o(cmd, output_path + "ragtag.scaffolds.fasta")
  File "/public/home/miniconda3/envs/ngs/lib/python3.6/site-packages/ragtag_utilities/utilities.py", line 91, in run_o
    raise RuntimeError('Failed : %s > %s' % (" ".join(cmd), out))
RuntimeError: Failed : ragtag_agp2fasta.py 
genome/gems41/ragtag_output/ragtag.scaffolds.agp /genome/g41/genome.nextpolish.fa > /genome/g41/ragtag_ou
tput/ragtag.scaffolds.fasta

Any suggestions? 
Thanks

**Comment by malonge** [comment] 2020-07-30 13:17
Hi there,

Can you share your command? The first thing to try is gripping for `ctg002980_np1212` in your query assembly. If it is there, then the next thing I would try is rerunning with the `-w` command. Sometimes this error can occur when RagTag retains preexisting intermediate files that should be updated.

**Comment by DengHAU** [comment] 2020-07-31 01:27
Thanks for your kindly reply. This is the command I used: `ragtag.py scaffold B73.ref.fa genome.nextpolish.fa -r -t 24`. The sequence name is there. I will give a try using `-w`. And I also find a **BUG** in the AGP file. After scaffolding all contigs were also treated as unplaced contig with a  weird name. The right contig name like "ctg002980_np1212", this contig name were also presented in unpalced contig with name “ctg002980_np12”. All other contigs have the same issue. Is this a bug someone also encountered?
Thanks！

**Comment by malonge** [comment] 2020-07-31 13:01
Hi there,

That is interesting. Can you send an example line of the AGP file? And are you saying that every contig is unplaced? To confirm if the AGP is invalid, I would use the [AGP validation utility](https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Validation/). If you download the command line version, you can check that the assemblies are consistent with the AGP. You can do something like this:

`agp_validate -comp ragtag.scaffolds.fasta genome.nextpolish.fa ragtag.scaffolds.agp`

Thanks

**Comment by DengHAU** [comment] 2020-08-01 03:54
Hi there,

The `ragtag_agp2fasta.py` step was died, I didn't got the the file `ragtag.scaffolds.fasta`. So I can't run `agp_validate` command. Here is my original ctg_name [https://github.com/DengHAU/test/blob/master/ctg.name.txt](url) and the agp file [https://github.com/DengHAU/test/blob/master/ragtag.scaffolds.agp](url) .May be it's a good idea to give each contig name a randem sequence and reproduce the error to fix it if it is a bug. 

Thanks a lot!

**Comment by malonge** [comment] 2020-08-01 13:05
Hi there,

Yes I can see that the AGP file is definitely incorrect. Would you be willing to share your `genome.nextpolish.fa`. I believe there might be something going on with pysam and I would like to try to reproduce the error. As far as I can tell right now, it is something here:

https://github.com/malonge/RagTag/blob/fb2f7ca523075d323d3f93b709e6304360c539d6/ragtag_scaffold.py#L131-L134

So maybe pysam shaves off the "12" suffix for some reason. That would explain both of your issues. I also wonder if the same thing happens when using `-C`.

**Comment by malonge** [comment] 2020-08-01 13:43
I was not able to reproduce the error using your fasta headers with fake sequence. So please let me know if you are able to reproduce it, or else I will need your fasta file.

Thanks

**Comment by DengHAU** [comment] 2020-08-03 01:59
I have e-mailed you the genome file. Hopely, it can helps.

**Comment by DengHAU** [comment] 2020-08-03 02:06
> Hi there,
> 
> Yes I can see that the AGP file is definitely incorrect. Would you be willing to share your `genome.nextpolish.fa`. I believe there might be something going on with pysam and I would like to try to reproduce the error. As far as I can tell right now, it is something here:
> 
> https://github.com/malonge/RagTag/blob/fb2f7ca523075d323d3f93b709e6304360c539d6/ragtag_scaffold.py#L131-L134
> 
> So maybe pysam shaves off the "12" suffix for some reason. That would explain both of your issues. I also wonder if the same thing happens when using `-C`.
> 
> If it is easier, you can send files to [malonge11@gmail.com](mailto:malonge11@gmail.com).
> 
> Or, if you are comfortable enough with python, you can check things on your end. In the same RagTag python environment, do the following:
> 
> ```
> python
> >>> import pysam
> >>> fai = pysam.FastaFile('genome.nextpolish.fa') 
> >>> all_seqs = fai.references
> >>> all_seqs
> ```
> 
> And check to see if the "12" is shaved off of the header names.
> 
> Thanks

![image](https://user-images.githubusercontent.com/29788898/89139303-d6803000-d570-11ea-9122-c9471049f67f.png)

**The "12" is shaved off of the header names.**

**Comment by malonge** [comment] 2020-08-03 02:12
Hi there,

Thanks for sharing the data. I haven't received the email yet, but once I have it, it will be useful for debugging.

So we can confirm that something is going on with pysam. I suppose it is either something specific to your fasta file or something specific to your environment (like your pyasm version). I will try to reproduce the error on my end, and in the meantime, I suggest you delete your `genome.nextpolish.fa.fai` and make sure that you are running RagTag with a [compatible pysam version](https://github.com/malonge/RagTag/wiki/Installation). Maybe that will solve the issue.

Thanks

**Comment by DengHAU** [comment] 2020-08-03 02:22
Hi,

I used 'pip install RagTag'. My pysam version is '0.16.0.1' > 0.15.2. Mybe it is OK. BTW, RaGOO works well.

Thanks.

**Comment by malonge** [comment] 2020-08-03 03:05
Ok so then I suppose it is something with your particular fasta file. I will try to reproduce the error on my end. Unfortunately, I still have not received your email. I'll keep an eye out.

Good to know that it works with RaGOO, which makes sense given that RaGOO does not use pysam.

**Comment by malonge** [comment] 2020-08-03 03:27
Also, I am not sure if you looked at this yet but I suggest you take a look at your `genome.nextpolish.fa.fai` file. I wonder if that is the source of the incorrect header names.

**Comment by DengHAU** [comment] 2020-08-03 04:42
Yes! `genome.nextpolish.fa.fai` is the source of the incorrect header names.

**Comment by DengHAU** [comment] 2020-08-03 04:48
> Ok so then I suppose it is something with your particular fasta file. I will try to reproduce the error on my end. Unfortunately, I still have not received your email. I'll keep an eye out.
> 
> Good to know that it works with RaGOO, which makes sense given that RaGOO does not use pysam.

I don't have gmail, so maybe try to find it out in the Spam box.

**Comment by malonge** [comment] 2020-08-03 13:02
Hi there,

So if you delete `genome.nextpolish.fa.fai` and remake it with `samtools faidx`, is the new file correct? 

I bet I didn't get the email because the attachment was too large. If you send me just your email address I can open up a google drive folder for you to put the fasta file in.

**Comment by DengHAU** [comment] 2020-08-03 13:09
Hi there,

`samtools faidx` works well. The index file is correct. My email address is: dchena@126.com.

**Comment by malonge** [comment] 2020-08-03 21:08
Hi there, using [this B73 reference](https://www.ncbi.nlm.nih.gov/assembly/GCF_000005005.2) I was unable to reproduce your error. It sounds like the problem stemmed from a incorrect fasta index file (`genome.nextpolish.fa.fai`). I bet if you delete that and rerun, it will work. If not you already confirmed that `samtools faidx` produces a correct fasta index file, so you can just delete the incorrect index and replace it with samtools prior to running ragtag. Pysam will not remake your index file if it is already there. Certainly, I don't think there is any indication of a bug in RagTag so I will close the issue. Please let me know if anything comes up.

**Closed by malonge** 2020-08-03 21:08 UTC

**Comment by DengHAU** [comment] 2020-08-04 01:37
Thank you for your patience! I deleted the fasta index file and rerun, it worked. Maybe it's a good idea to force pysam to rewrite the exit index file to avoid issues like this using an incorrect index for some reason. And this index step costs less and run fast. Just my personal opinion.

**Comment by malonge** [comment] 2020-08-04 13:20
Hi there,

I appreciate your feedback. I am inclined to keep it the way it is because faulty fai files are pretty rare and this can save lot of time for larger genomes. But I will keep an eye out to see if this problem is more common than I realize.

Thanks
